version: "3.9"

services:
  agent:
    build: .
    env_file: .env
    restart: unless-stopped
    expose:
      - "4000"
    networks: [backend]

  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /etc/letsencrypt/live/8008111.xyz/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/8008111.xyz/privkey.pem:/certs/privkey.pem:ro
    networks: [backend]

networks:
  backend:
    driver: bridge
